name: Formatting

on: [pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install formatter
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Check if formatting is needed for all files
        run: if black --check .; then export IS_BLACK_NEEDED=0; else export IS_BLACK_NEEDED=1; fi
      - name: If needed, commit black changes to a new pull request
        if: ${{ env.IS_BLACK_NEEDED }} -eq 1
        run: |
          black .
          isort --profile black .
          git config --global user.name ${{ github.actor }}
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'          
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Fixup! Format Python code with psf/black"
          git push
