name: Linting

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Lint all files
        run: |
          # Specific flake8 errors that do not involve whitespaces. Syntax errors, == or is mistakes, type hints mistakes, undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.mypy_cache,.venv,.vscode,.github,.git,data
